---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo

  # More roles can be added here too.
  #roles: 
  # - { role: pcextreme.nginx } 
  # 
  pre_tasks:
   - name: update apt
     apt: update_cache=yes 

   - name: install add_apt command 
     apt: name=python-software-properties state=installed 

   - name: install nginx  
     apt: name=nginx
  
